image: docker:19.03.12

stages:
  - build
  - release

services:
  - docker:19.03.12-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  PROJECT_NAME: majortom327/docgen
  CONTAINER_TEST_IMAGE: $PROJECT_NAME:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $PROJECT_NAME:latest

before_script:
  - docker login -u majortom327 -p $DOCKER_TOKEN
  - docker pull $PROJECT_NAME

build-image:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  dependencies:
    - build-image
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master