version: '2'
services:
  gotenberg:
    image: thecodingmachine/gotenberg
    ports: []
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  docgen:
    build:
      context: .
    depends_on:
      - mongo
      - gotenberg
    ports:
      - '3000:3000'
    restart: always
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      MONGO_URL: 'mongodb://mongo:27017/cats'
